dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.3
  - name: memcached
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.0.3
  - condition: mariadb.enabled
    name: mysql_metrics
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.1
  - name: rabbitmq
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.9
  - alias: rabbitmq_notifications
    condition: audit.enabled
    name: rabbitmq
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.9
  - name: region_check
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.2
  - name: utils
    repository: file://../../openstack/utils
    version: 0.1.1
