apiVersion: batch/v1
kind: Job
metadata:
  name: neutron-migration
  labels:
    system: openstack
    type: configuration
    component: neutron
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: neutron-migration
          image: {{.Values.global.registry}}/loci-neutron:{{default .Values.imageVersion | required "Please set neutron.imageVersion or similar"}}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "neutron-db-manage upgrade head"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "{{ .Release.Name }}-mariadb"
            - name: PGAPPNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /etc/neutron
              name: etc-neutron
              readOnly: true
      volumes:
        - name: etc-neutron
          projected:
            defaultMode: 420
            sources:
            - configMap:
                items:
                - key: neutron.conf
                  path: neutron.conf
                - key: neutron-lbaas.conf
                  path: neutron-lbaas.conf
                - key: ml2-conf.ini
                  path: plugins/ml2/ml2-conf.ini
                name: neutron-etc
