{{- if .Values.nanny.enabled }}
{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: neutron-nanny
  namespace: monsoon3
  labels:
    system: openstack
    service: neutron-nanny

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        component: neutron-nanny
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: neutron-etc
          configMap:
            name: neutron-etc
      containers:
{{- if .Values.nanny.cleanup_pending_lb.enabled }}
        - name: cleanup-pending-lb
          image: {{.Values.global.registry}}/neutron-nanny:{{.Values.imageVersionNanny | required "Please set neutron.imageVersionNanny"}}
          imagePullPolicy: IfNotPresent
          command:
            - dumb-init
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "{{ if not .Values.nanny.debug }}/bin/bash /scripts/neutron-cleanup-pending-lb.sh{{ else }}sleep inf{{ end }}"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEPENDENCY_SERVICE
              value: "neutron-mariadb,neutron-server"
            - name: NEUTRON_CLEANUP_PENDING_LB_ENABLED
              value: {{ .Values.nanny.cleanup_pending_lb.enabled | quote }}
            - name: NEUTRON_CLEANUP_PENDING_LB_DRY_RUN
              value: {{ .Values.nanny.cleanup_pending_lb.dry_run | quote }}
            - name: NEUTRON_CLEANUP_PENDING_LB_INTERVAL
              value: {{ .Values.nanny.cleanup_pending_lb.interval | quote }}
            - name: NEUTRON_CLEANUP_PENDING_LB_ITERATIONS
              value: {{ .Values.nanny.cleanup_pending_lb.iterations | quote }}
          volumeMounts:
            - mountPath: /neutron-etc
              name: neutron-etc
{{- end }}
{{- end }}
