dependencies:
  - name: postgresql
    condition: postgresql.enabled
    repository: file://../../common/postgresql
    version: 0.3.0
  - name: pgmetrics
    condition: postgresql.enabled
    repository: file://../../common/pgmetrics
    version: 0.1.0
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.21
  - name: mariadb
    alias: mariadb_api
    condition: mariadb_api.enabled
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.21
  - condition: mariadb.enabled
    name: mysql_metrics
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.1
  - name: rabbitmq
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.4
  - name: memcached
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.0.2
  - name: rabbitmq
    alias: rabbitmq_notifications
    condition: audit.enabled
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.4
  - name: utils
    repository: file://../../openstack/utils
    version: 0.1.1
  - name: postgresql
    alias: postgresql_cell2
    condition: cell2.enabled, postgresql.enabled
    repository: file://../../common/postgresql
    version: 0.3.0
  - name: mariadb
    alias: mariadb_cell2
    condition: cell2.enabled, mariadb.enabled
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.21
  - name: rabbitmq
    alias: rabbitmq_cell2
    condition: cell2.enabled
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.4
  - name: region_check
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.1
